name: VPS-deploy

on:
  push:
    branches:
      - master

jobs:

  deploy:
    environment: stage
    runs-on: ubuntu-latest

    steps:

      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd go-csv-crud-example
            git pull origin master

            docker-compose up -d --build